name: Deploy to GitHub pages

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build static files
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm ci
      - run: npm run build-prod

      - name: Init new repo in dist folder and commit generated files
        run: |
          cd build
          git init
          git add -A
          git config --local user.email "humberto-xingu@live.com"
          git config --local user.name "GitHub Action"
          git config --global --add safe.directory '*'
          git commit -m 'deploy'

      - name: Force push to destination branch
        uses: ad-m/github-push-action@v0.5.0
        with:
          # Token for the repo
          # Can be passed in using $\{{ secrets.GITHUB_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Destination branch to push changes
          branch: gh-pagesv2
          # Use force push to fully overwrite the destination branch
          force: true
          # We have to push from the folder where files were generated.
          # Same were the new repo was initialized in the previous step
          directory: ./build


